### ISSUE TITLE
[cms] css cleanup / refactor checklist

### ISSUE THREAD

**Issue by perpetualgrimace** [Datawheel/canon#548]
- [x] split out cms.css into partials
- [x] move light-theme.css & dark-theme.css style to relevant components
- [x] remove old/unused css
- [x] import mixins.css in each file
- [x] refactor/integrate layout styles
- [x] refactor/integrate shame.css
- [x] create `<Section>` component for title/description/cards sections
  - [x] use `<Section>` component for profiles
  - [x] use `<Section>` component for topics
  - [x] use `<Section>` component for formatter editor
  - [x] use `<Section>` component for stories
  - [x] use `<Section>` component for story topic editor
- [x] create `<Button>` component
- [x] create `<Status>` component & consolidate styles
- [x] create `<SidebarTree>` wrapper component
- [x] create generic `<Card>` wrapper component
~- [ ] create `<Dialog>` wrapper component~

**Comment by perpetualgrimace** [comment]
Keeping track of my work on the [cms-refactor](https://github.com/Datawheel/canon/commits/cms-refactor) branch.

**Comment by davelandry** [comment]
@perpetualgrimace ...is this done?

**Comment by perpetualgrimace** [comment]
lol we can probably close it and make a separate issue for dialogs
